# Generated by Django 2.0.6 on 2018-06-15 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('opinion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('sinopsis', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Comentario')),
            ],
        ),
    ]
