# Generated by Django 2.0.6 on 2018-06-15 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroFila', models.IntegerField()),
                ('numeroAsiento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(blank=True, max_length=200, null=True)),
                ('opinion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('sinopsis', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroEntradas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroSala', models.IntegerField()),
                ('numeroFilas', models.IntegerField()),
                ('numeroAsientosFila', models.IntegerField()),
                ('numeroAsientosUltimaFila', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('pelicula', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cine.Pelicula')),
                ('sala', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cine.Sala')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='sesion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cine.Sesion'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='pelicula',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cine.Pelicula'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='reserva',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cine.Reserva'),
        ),
    ]
